use_frameworks!

platform :ios, '8.0'

target 'WGColorTool_Example' do
  pod 'WGColorTool', :path => '../'

  target 'WGColorTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
